# =================================================================
#  Docker Compose for Family Budget Management Tool (Corrected)
# =================================================================

# Define a network for our containers to communicate on
networks:
  budget-net:
    driver: bridge

services:
  # 1. The Backend Node.js/Express API Server
  server:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.server
    container_name: budget_app_server
    restart: unless-stopped
    volumes:
      - budget_db_data:/usr/src/app/data/sqlite
    # Connect the server to our custom network
    networks:
      - budget-net
    environment:
      - NODE_ENV=production

  # 2. The Frontend Service (React App + Nginx Proxy)
  client:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.client
    container_name: budget_app_client
    ports:
      # Expose the application on port 80 of your Mac
      - "80:80"
    restart: unless-stopped
    # The client depends on the server being started
    depends_on:
      - server
    # Connect the client to the same custom network
    networks:
      - budget-net

volumes:
  budget_db_data: {}